name: WegnerDesign
description: "Nerdy Ramblings, Usually about Javascript"
url: http://www.wegnerdesign.com
safe: true
lsi: false
highlighter: true
paginate: 10
markdown: redcarpet
permalink: :categories/:title
