name: WegnerDesign
description: "Nerdy Ramblings, Usually about Javascript"
url: https://www.wegnerdesign.com
safe: true
lsi: false
highlighter: pygments
paginate: 10
markdown: redcarpet
permalink: :categories/:title
