name: WegnerDesign
description: "Nerdy Ramblings, Usually about Javascript"
url: http://www.wegnerdesign.com
safe: true
lsi: false
pygments: true
paginate: 10
auto: true
markdown: redcarpet
permalink: :categories/:title
